yarnPath: .yarn/releases/yarn-3.2.0.cjs

nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3":
    peerDependencies:
      typescript: "*"
  "@shopify/eslint-plugin@41":
    peerDependencies:
      "@babel/core": "*"
      graphql: "*"
      prettier: "*"
      typescript: "*"
  eslint-config-hardcore@24:
    peerDependencies:
      "@babel/core": "*"
      graphql: "*"
  eslint-plugin-graphql@4:
    peerDependencies:
      typescript: "*"
  graphql-config@3:
    peerDependencies:
      typescript: "*"

